name: API - Production (master)

on:
  push:
    branches:	
      - master
  workflow_dispatch:

jobs:	
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master

    - name: Set up .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '5.0.x'

    - name: Build with dotnet
      run: dotnet build gb-manager-api/gb-manager-api.csproj --configuration Release

    - name: dotnet publish
      run: dotnet publish gb-manager-api/gb-manager-api.csproj -c Release -o ${{env.DOTNET_ROOT}}/myapp

    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v1
      with:
        app-name: 'massificados-api'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_ceef5865c5ad4aed9eb35ec8c3dc6c5d }}
        package: ${{env.DOTNET_ROOT}}/myapp
