name: API - Production (master)

on:
  push:
    branches:	
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '5.0.x'

    - name: Build with dotnet
      run: dotnet build gb-manager-api/gb-manager-api.csproj --configuration Release

    - name: dotnet publish
      run: dotnet publish gb-manager-api/gb-manager-api.csproj -c Release -o ${{env.DOTNET_ROOT}}/myapp

    - name: Upload artifact for deployment job
      uses: actions/upload-artifact@v2
      with:
        name: .net-app
        path: ${{env.DOTNET_ROOT}}/myapp

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Download artifact from build job
      uses: actions/download-artifact@v2
      with:
        name: .net-app

    - name: Deploy to Azure Web App stg01
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'gbceilandia'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_ceef5865c5ad4aed9eb35ec8c3dc6c5d }}
        package: .
